projet_burger_start:
    path:     /
    defaults: { _controller: ProjetBurgerBundle:Burger:index }
projet_burger_homepage:
    path:     /burger
    defaults: { _controller: ProjetBurgerBundle:Burger:index }
projet_burger_catalog:
    path:     /catalog
    defaults: { _controller: ProjetBurgerBundle:Burger:catalog}
projet_burger_ahomepage:
    path:     /aburger
    defaults: { _controller: ProjetBurgerBundle:Burger:aindex}
projet_burger_nproductform:
    path:     /newProduct
    defaults: { _controller: ProjetBurgerBundle:Burger:nproductform}
projet_burger_pdescription:
    path:     /description/{id}
    defaults: { _controller: ProjetBurgerBundle:Burger:pdescription}
    requirements:
        id:   \d+
projet_burger_ncityform:
    path:     /newCity
    defaults: { _controller: ProjetBurgerBundle:Burger:ncityform}