projet_burger_start:
    path:     /
    defaults: { _controller: ProjetBurgerBundle:Burger:index }
projet_burger_homepage:
    path:     /burger/{id}
    defaults: { _controller: ProjetBurgerBundle:Burger:index, id: 0 }
    requirements:
        id:   \d+
projet_burger_catalog:
    path:     /catalog
    defaults: { _controller: ProjetBurgerBundle:Burger:catalog}
projet_burger_ahomepage:
    path:     /aburger
    defaults: { _controller: ProjetBurgerBundle:Burger:aindex}
projet_burger_nproductform:
    path:     /newProduct/{id}
    defaults: { _controller: ProjetBurgerBundle:Burger:nproductform, id: 0}
    requirements:
        id:   \d+
projet_burger_pdescription:
    path:     /description/{id}
    defaults: { _controller: ProjetBurgerBundle:Burger:pdescription}
    requirements:
        id:   \d+
projet_burger_ncityform:
    path:     /newCity
    defaults: { _controller: ProjetBurgerBundle:Burger:ncityform}
projet_burger_dproduct:
    path:     /deleteProduct
    defaults: { _controller: ProjetBurgerBundle:Burger:dproduct}
projet_burger_vdproduct:
    path: /validateDeleting
    defaults: { _controller: ProjetBurgerBundle:Burger:vdproduct}
projet_burger_buaccount:
    path:     /blockAccount
    defaults: { _controller: ProjetBurgerBundle:Burger:buaccount}
projet_burger_vbuaccount:
    path:     /validateAccountOperation
    defaults: { _controller: ProjetBurgerBundle:Burger:vbuaccount}
projet_burger_eproduct:
    path:     /editProduct
    defaults: { _controller: ProjetBurgerBundle:Burger:eproduct}
projet_burger_veproduct:
    path:     /validateEditing
    defaults: {_controller: ProjetBurgerBundle:Burger:veproduct}
projet_burger_valide:
    path:     /valide
    defaults: { _controller: ProjetBurgerBundle:Burger:valide}
projet_burger_nuserform:
    path:     /newUser
    defaults: { _controller: ProjetBurgerBundle:Burger:nuser}
projet_burger_usercon:
    path:     /validateUser
    defaults: { _controller: ProjetBurgerBundle:Burger:usercon}
projet_burger_admincon:
    path:     /validateAdmin
    defaults: { _controller: ProjetBurgerBundle:Burger:admincon}